[package]
name = "one-time-signature"
version = "0.1.0"
edition = "2024"

[dependencies]
digest = "0.11.3"
sha2 = { version = "0.11.0", optional = true, default-features = false }
shake = { version = "0.1.0", optional = true, default-features = false }

[features]
rfc8391 = ["sha2", "shake"]
rfc8554 = ["sha2"]
fips205 = ["sha2", "shake"]

[dev-dependencies]
criterion = "0.8.2"
